name = "onlyuppieswatcher"
main = "src/main.ts"
compatibility_date = "2026-08-02"
minify = true
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true
workers_dev = false
preview_urls = false
send_metrics = false

# mirror of file data, for easy download to populate a list
[[r2_buckets]]
binding = "R2"
bucket_name = "onlyuppies2"

# used for bookkeeping records, i.e. which posts we've seen
[[kv_namespaces]]
binding = "KV"
id = "caf272d935da40e39b3e741f7bfd8faf"

[triggers]
crons = ["*/5 * * * *"]

[observability]
enabled = true
head_sampling_rate = 1

# 30s CPU limit
[limits]
cpu_ms = 30000

[[queues.producers]]
queue = "bsky-thread-watcher"
binding = "THREAD_UPDATE_QUEUE"

[[queues.consumers]]
queue = "bsky-thread-watcher"
max_batch_size = 3
max_batch_timeout = 3
retry_delay = 20
max_retries = 10

# no webhook = no maidens
[secrets]
required=["DISCORD_WEBHOOK", "BSKY_APP_PASSWORD"]

# closest to microcosm data
[placement]
region = "gcp:northamerica-northeast2-a"

[vars]
# constrain yourself
MAX_GALLERY_IMAGES=4
MAX_RECURSE_DEPTH=2

# this is the did for socksthewolf.com, any posts with this DID will not be processed.
# change the did to add something else
SKIP_DID="did:plc:2vueglf2njr5gvdbaf75ih6a"

# user id for post liking
BSKY_USERNAME="socksthewolf.com"

# if the number of found records should be posted to the discord webhook
POST_RECORD_FINDINGS="false"

# what PDS to use to log into the network
DEFAULT_PDS="https://bsky.social"

# Custom user agent string
USER_AGENT="OnlyUppies4Fetcher"

# max scraping attempts, this should match whatever your queue.consumer.max_retries is set to
MAX_SCRAPE_ATTEMPTS = "10"

# target posts on atproto
# use pdsls.dev to get this link (check info tab for one click copy)
TARGET={"threads"=[
  "at://did:plc:2vueglf2njr5gvdbaf75ih6a/app.bsky.feed.post/3mso2qdbtvl22",
  "at://did:plc:2vueglf2njr5gvdbaf75ih6a/app.bsky.feed.post/3msxduqkcdk22",
  "at://did:plc:2vueglf2njr5gvdbaf75ih6a/app.bsky.feed.post/3mt2wgbshyc2o",
  "at://did:plc:2vueglf2njr5gvdbaf75ih6a/app.bsky.feed.post/3mtanaqrgws2k"
]}