name = "onlyuppieswatcher"
main = "src/main.ts"
compatibility_date = "2026-08-02"
minify = true
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true
workers_dev = false
preview_urls = false
send_metrics = false

[[r2_buckets]]
binding = "R2"
bucket_name = "onlyuppies"
remote = true

[[kv_namespaces]]
binding = "KV"
id = "743e785ed53f49cca04b90f105c0b84e"

[triggers]
crons = ["0 */1 * * *"] # run at every hour on the hour

[observability]
enabled = true
head_sampling_rate = 1

[secrets]
required=["WEBHOOK"]

[placement]
region = "gcp:northamerica-northeast2-a"

[vars]
# constrain yourself
MAX_GALLERY_IMAGES="4"
# socksthewolf.com
SKIP_DID="did:plc:2vueglf2njr5gvdbaf75ih6a"
# target post on atproto
# use pdsls.dev to get this link (check info tab)
TARGET=""